version: '2'
services:
### NGINX Server Container ##################################

    nginx:
      build:
        context: ./
        #args:
          #- PHP_UPSTREAM_CONTAINER=php-fpm
          #- PHP_UPSTREAM_PORT=9000
      volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./config/sites/:/etc/nginx/sites-available
        - ./www:/var/www
      ports:
        - "80:80"
        - "443:443"
### Volumes Setup #############################################

# volumes:
#   mysql:
#     driver: "local"
